import{b as l,l as p,r as v,a as S}from"./assets/api-ea25c3d4.js";import"./assets/vendor-8dea2054.js";const w=document.querySelector(".backdrop"),L=document.querySelector(".modal-wrapper"),f=document.querySelector(".modal-icons-list"),B=document.querySelector("body"),c=document.querySelector(".modal-btn-add"),d=document.querySelector(".congrats"),_=document.querySelector(".modal-close"),r={_id:"",title:"",author:"",list_name:"",book_image:"",description:"",amazon_buy_link:"",apple_buy_link:""};async function C(e){try{L.innerHTML="",f.innerHTML="";const t=await l.getBookDescription(e),s=j(t);L.insertAdjacentHTML("beforeend",s);const o=x(t);f.insertAdjacentHTML("beforeend",o),r._id=t._id,r.title=t.title,r.author=t.author,r.list_name=t.list_name,r.book_image=t.book_image,r.description=t.description,r.amazon_buy_link=t.buy_links[0].url,r.apple_buy_link=t.buy_links[1].url,b(c,e),c.addEventListener("click",T),_.addEventListener("click",q)}catch(t){console.log("Error fetching modal:",t)}}function $(e){w.classList.add("is-open"),B.classList.add("no-scroll"),C(e)}function j(e){return`
      <img class="modal-img-book" src="${e.book_image}" alt="book" />
      <ul class="modal-description-list">
      <li><p class="modal-description-list-title">${e.title}</p></li>
      <li><p class="modal-description-list-subtitle">${e.author}</p></li>
      <li>
        <p class="modal-description-list-text">
          ${e.description}
        </p>
      </li>
      </ul>`}function x(e){return`<li>
        <a class="modal-icon amazon" href="${e.buy_links[0].url}"><img class='modal-icon' src="./img/amazon.png" alt="" width='62' height='19' 
       /></a>
      </li>
      <li>
        <a class="modal-icon" href="${e.buy_links[1].url}"><img class='modal-icon' src="./img/applebook.png" alt="" width='33' height='32'
       /></a>
      </li>`}function b(e,t){p.isBookExsist(t)?(e.textContent="remove from the shopping list",e.classList.add("modal-btn-remove"),d.classList.add("modal-text-congratulations")):(e.textContent="add to shopping list",e.classList.remove("modal-btn-remove"),d.classList.remove("modal-text-congratulations"))}function T(e){c.textContent==="add to shopping list"?(I(r),b(c,r._id)):(A(r),b(c,r._id))}function q(){w.classList.remove("is-open"),B.classList.remove("no-scroll"),_.removeEventListener("click",q),c.removeEventListener("click",T)}function I(e){p.addBookToFavorites(e),d.textContent='Сongratulations! You have added the book to the shopping list. To delete, press the button "Remove from the shopping list".'}function A(e){p.removeBookFromFavorites(e),d.textContent=""}function k(e,t){u();try{const s=document.querySelector(".bestsellers-container");s.innerHTML="",v(".bestsellers-container",t),s.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const o=document.querySelector(".book-category-list"),n=e.map(({author:a,book_image:i,title:g,_id:y})=>S({author:a,book_image:i,title:g,_id:y})).join("");o.innerHTML=n,o.addEventListener("click",N)}catch{console.log("Error fetching modal:",error)}finally{m()}}async function N(e){if(e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let t=e.target.closest(".book-category-item").dataset.id;$(t)}}async function P(){u();try{const e=await l.getBestSellers();E(e),m()}catch(e){console.error("Error fetching best sellers:",e)}}function E(e){const t=document.querySelector(".bestsellers-container");t.innerHTML="",v(".bestsellers-container","Best Sellers Books"),t.insertAdjacentHTML("beforeend",'<ul class="bestsellers-list"></ul>');const s=document.querySelector(".bestsellers-list"),o=e.map(({books:a,list_name:i})=>`<li class="bestsellers-item">
              <h2 class="bestsellers-category-title">${i}</h2>
              <ul class="bestsellers-books-list"> 
                ${a.map(({title:g,author:y,book_image:M,_id:H})=>S({title:g,author:y,book_image:M,_id:H})).join(`
`)}
              </ul>
              <button class="bestsellers-btn" type="button" data-category="${i}">See more</button>
            </li>`).join(`
`);s.insertAdjacentHTML("beforeend",o);const n=document.querySelector(".bestsellers-list");n.addEventListener("click",D),n.addEventListener("click",z)}async function z(e){if(e.preventDefault(),e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let t=e.target.closest(".book-category-item").dataset.id;C(t)}}async function D(e){try{if(e.target.nodeName!=="BUTTON")return;let t=e.target.dataset.category;const s=document.querySelector(".sidebar-category-item"),o=document.querySelectorAll(".sidebar-category-item");window.scrollTo({top:0,behavior:"smooth"});const n=await l.getSelectedCategory(t);k(n,t),o.forEach(a=>{a.dataset.source===t&&(s.classList.remove("category-active"),a.classList.add("category-active"),a.scrollIntoView(!0))}),window.scrollTo({top:0,behavior:"smooth"})}catch(t){console.log("Error fetching modal:",t)}}const h={categoryContainer:document.querySelector(".sidebar-category-container"),categoryList:document.querySelector(".sidebar-category-list"),allCategory:document.querySelector(".all-category")};function F(e){return e.sort((s,o)=>s.list_name.localeCompare(o.list_name)),e.map(s=>`<li class='sidebar-category-item' data-source="${s.list_name}">${s.list_name}</li>`).join("")}(async()=>{try{const e=await l.getCategoryList(),t=F(e);h.categoryList.insertAdjacentHTML("beforeend",t)}catch(e){console.log(e)}})();h.allCategory.addEventListener("click",async e=>{u();try{const t=await l.getBestSellers();ca,E(t),m()}catch(t){console.log(t)}});h.categoryList.addEventListener("click",async e=>{if(e.target.classList.contains("sidebar-category-item")){const t=e.target.dataset.source;document.querySelectorAll(".sidebar-category-item").forEach(o=>{o.classList.remove("category-active")}),e.target.classList.add("category-active"),window.scrollTo({top:0,behavior:"smooth"}),u();try{if(!e.target.classList.contains("all-category")){const o=await l.getSelectedCategory(t);k(o,t),o.length===0?notification(`Sorry! There are no books available in the category "${t}".`):(k(o,t),m())}}catch(o){console.log(o)}}});P();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".scroll-up");e.classList.remove("show"),window.addEventListener("scroll",function(){window.scrollY>650?e.classList.add("show"):e.classList.remove("show")}),e.addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth"})})});function u(){document.querySelector(".loader-container").classList.remove("is-hidden")}function m(){document.querySelector(".loader-container").classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers2.js.map
