import{b as d,l as g,r as b,a as p}from"./assets/api-9ed69dfe.js";import"./assets/vendor-8dea2054.js";const u=async e=>{const o=document.querySelector(".modal-wrapper"),a=document.querySelector(".modal-icons-list"),r=document.querySelector(".modal-window");try{const t=await d.getBookDescription(e);o.innerHTML="",a.innerHTML="";const n=`
      <img class="modal-img-book" src="${t.book_image}" alt="book" />
      <ul class="modal-description-list">
      <li><p class="modal-description-list-title">${t.title}</p></li>
      <li><p class="modal-description-list-subtitle">${t.author}</p></li>
      <li>
        <p class="modal-description-list-text">
          ${t.description}
        </p>
      </li>
      </ul>`;o.insertAdjacentHTML("beforeend",n);const l=`<li class="modal-icons-wrapper-1">
        <a class="modal-icon" href="${t.buy_links[0].url}"><img class='modal-icon' src="../img/amazon.png" alt="" width='62' height='19' 
       /></a>
      </li>
      <li class="modal-icons-wrapper-2">
        <a class="modal-icon" href="${t.buy_links[1].url}"><img class='modal-icon' src="../img/applebook.png" alt="" width='33' height='32'
       /></a>
      </li>`;a.insertAdjacentHTML("beforeend",l);let s=document.querySelector(".modal-btn-add");const m={_id:t._id,title:t.title,author:t.author,list_name:t.list_name,book_image:t.book_image,description:t.description,amazon_buy_link:t.buy_links[0].url,apple_buy_link:t.buy_links[1].url};if(g.isBookExsist(t._id)){let c=function(){g.removeBookFromFavorites(t._id),s.textContent="add to shopping list",s.classList.remove("modal-btn-remove"),s.removeEventListener("click",c),u(t._id)};s.textContent="remove from the shopping list";const i=`<p class="modal-text-congratulations">
      Сongratulations! You have added the book to the shopping list. To delete,
      press the button "Remove from the shopping list".
    </p>`;r.insertAdjacentHTML("beforeend",i),s.addEventListener("click",c)}else{let c=function(){g.addBookToFavorites(m),s.textContent="remove from the shopping list",s.classList.add("modal-btn-remove"),s.removeEventListener("click",c),u(t._id)};s.textContent="add to shopping list",s.addEventListener("click",c);const i=document.querySelector(".modal-text-congratulations");i!==null&&i.remove()}}catch(t){console.log("Error fetching modal:",t)}},k=document.querySelector(".backdrop"),S=document.querySelector(".modal-close"),L=document.querySelector("body");S.addEventListener("click",()=>{k.classList.remove("is-open"),L.classList.remove("no-scroll")});function h(){k.classList.add("is-open"),L.classList.add("no-scroll")}function f(e,o){const a=document.querySelector(".bestsellers-container");a.innerHTML="",b(".bestsellers-container",o),a.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const r=document.querySelector(".book-category-list"),t=e.map(({author:n,book_image:l,title:s,_id:m})=>p({author:n,book_image:l,title:s,_id:m})).join("");r.innerHTML=t,r.addEventListener("click",w)}async function w(e){if(e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let o=e.target.closest(".book-category-item").dataset.id;u(o),h()}}async function C(){try{const e=await d.getBestSellers();v(e)}catch(e){console.error("Error fetching best sellers:",e)}}function v(e){const o=document.querySelector(".bestsellers-container");o.innerHTML="",b(".bestsellers-container","Best Sellers Books"),o.insertAdjacentHTML("beforeend",'<ul class="bestsellers-list"></ul>');const a=document.querySelector(".bestsellers-list"),r=e.map(({books:n,list_name:l})=>`<li class="bestsellers-item">
              <h2 class="bestsellers-category-title">${l}</h2>
              <ul class="bestsellers-books-list"> 
                ${n.map(({title:s,author:m,book_image:i,_id:c})=>p({title:s,author:m,book_image:i,_id:c})).join(`
`)}
              </ul>
              <button class="bestsellers-btn" type="button" data-category="${l}">See more</button>
            </li>`).join(`
`);a.insertAdjacentHTML("beforeend",r);const t=document.querySelector(".bestsellers-list");t.addEventListener("click",B),t.addEventListener("click",q)}async function q(e){if(e.preventDefault(),e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let o=e.target.closest(".book-category-item").dataset.id;u(o),h()}}async function B(e){if(e.target.nodeName!=="BUTTON")return;let o=e.target.dataset.category;const a=document.querySelector(".sidebar-category-item");document.querySelectorAll(".sidebar-category-item").forEach(n=>{n.dataset.source===o&&(a.classList.remove("category-active"),n.classList.add("category-active"))});const t=await d.getSelectedCategory(o);f(t,o)}const y={categoryContainer:document.querySelector(".sidebar-category-container"),categoryList:document.querySelector(".sidebar-category-list"),allCategory:document.querySelector(".all-category")};function T(e){return e.map(a=>`<li class='sidebar-category-item' data-source="${a.list_name}">${a.list_name}</li>`).join("")}(async()=>{try{const e=await d.getCategoryList(),o=T(e);y.categoryList.insertAdjacentHTML("beforeend",o)}catch(e){console.log(e)}})();y.allCategory.addEventListener("click",async e=>{try{const o=await d.getBestSellers();v(o)}catch(o){console.log(o)}});y.categoryList.addEventListener("click",async e=>{if(e.target.classList.contains("sidebar-category-item")){const o=e.target.dataset.source;document.querySelectorAll(".sidebar-category-item").forEach(r=>{r.classList.remove("category-active")}),e.target.classList.add("category-active");try{if(!e.target.classList.contains("all-category")){const r=await d.getSelectedCategory(o);f(r,o)}}catch(r){console.log(r)}}});C();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".scroll-up");e.classList.remove("show"),window.addEventListener("scroll",function(){window.scrollY>650?e.classList.add("show"):e.classList.remove("show")}),e.addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth"})})});window.addEventListener("load",()=>{let e=document.querySelector(".background");e.classList.add("hide"),setTimeout(()=>{e.remove()},600)});
//# sourceMappingURL=commonHelpers2.js.map
