import{b as d,l as f,r as p,a as S}from"./assets/api-a75f33f1.js";import"./assets/vendor-8dea2054.js";const m=document.querySelector(".backdrop"),v=document.querySelector(".modal-wrapper"),w=document.querySelector("body"),i=document.querySelector(".modal-btn-addremove"),g=document.querySelector(".congrats"),B=document.querySelector(".modal-close"),s={_id:"",title:"",author:"",list_name:"",book_image:"",description:"",amazon_buy_link:"",apple_buy_link:""};async function $(e){try{v.innerHTML="",g.innerHTML="";const t=await d.getBookDescription(e);s._id=t._id,s.title=t.title,s.author=t.author,s.list_name=t.list_name,s.book_image=t.book_image,s.description=t.description,s.amazon_buy_link=t.buy_links[0].url,s.apple_buy_link=t.buy_links[1].url;const o=j(t);v.insertAdjacentHTML("beforeend",o),h(i,e),i.addEventListener("click",_),B.addEventListener("click",y),document.addEventListener("keydown",T),m.addEventListener("click",M)}catch(t){console.log("Error fetching modal:",t)}}function C(e){m.classList.add("is-open"),w.classList.add("no-scroll"),$(e)}function j(e){return`
      <img class="modal-img-book" src="${e.book_image}" alt="book" />
        
      <div class="modal-book-container-right">
        <div class="modal-book-container">
          <div class="modal-book-info">
            <h3 class="modal-description-title">${e.title}</h3>
            <p class="modal-description-author">${e.author}</p>
          </div>
          <p class="modal-book-description">${e.description}</p>
          <ul class="modal-icons-list">
          <li>
            <a class="modal-book-link" href="${e.buy_links[0].url}" target="_blank"><img class='modal-link-icon-amazon' src="/img/amazon-n.png" alt="" width='62' height='19' 
            /></a>
          </li>
          <li>
            <a class="modal-book-link" href="${e.buy_links[1].url}" target="_blank"><img class='modal-link-icon-apple' src="/img/apple-n.png" alt="" width='33' height='32'
            /></a>
          </li>
          </ul>
        </div>
      </div>`}function h(e,t){f.isBookExsist(t)?(e.textContent="remove from the shopping list",g.classList.add("modal-text-congratulations")):(e.textContent="add to shopping list",g.classList.remove("modal-text-congratulations"))}function _(e){i.textContent==="add to shopping list"?(A(s),h(i,s._id)):(x(s),h(i,s._id))}function T(e){e.key==="Escape"&&y()}function M(e){e.target===m&&y()}function y(){m.classList.remove("is-open"),w.classList.remove("no-scroll"),B.removeEventListener("click",y),i.removeEventListener("click",_),document.removeEventListener("keydown",T),m.removeEventListener("click",M)}function A(e){f.addBookToFavorites(e),g.textContent='Сongratulations! You have added the book to the shopping list. To delete, press the button "Remove from the shopping list".'}function x(e){f.removeBookFromFavorites(e),g.textContent=""}function q(e,t){if(u(),e.length===0)try{const o=document.querySelector(".bestsellers-container");o.innerHTML="",p(".bestsellers-container",t),o.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const n=document.querySelector(".book-category-list"),r='<p class = "category-text-empty">Sorry, no books were found for the given category</p>';n.innerHTML=r}catch{console.log("Error fetching modal:",error)}finally{c()}else try{const o=document.querySelector(".bestsellers-container");o.innerHTML="",p(".bestsellers-container",t),o.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const n=document.querySelector(".book-category-list"),r=e.map(({author:l,book_image:a,title:b,_id:k})=>S({author:l,book_image:a,title:b,_id:k})).join("");n.innerHTML=r,n.addEventListener("click",I)}catch{console.log("Error fetching modal:",error)}finally{c()}}async function I(e){if(e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let t=e.target.closest(".book-category-item").dataset.id;C(t)}}async function N(){try{const e=document.querySelector(".bestsellers-container");e.innerHTML="",u();const t=await d.getBestSellers();E(t)}catch(e){console.error("Error fetching best sellers:",e)}}function E(e){const t=document.querySelector(".bestsellers-container");c(),t.innerHTML="",p(".bestsellers-container","Best Sellers Books"),t.insertAdjacentHTML("beforeend",'<ul class="bestsellers-list"></ul>');const o=document.querySelector(".bestsellers-list"),n=e.map(({books:r,list_name:l})=>`<li class="bestsellers-item">
      <h2 class="bestsellers-category-title">${l}</h2>
      <ul class="bestsellers-books-list">${r.map(({title:a,author:b,book_image:k,_id:H})=>r.length===0?'<p class="category-empty">Sorry, no books were found for the given category!</p>':S({title:a,author:b,book_image:k,_id:H})).join(`
`)}
        </ul>
        <button class="bestsellers-btn" type="button" data-category="${l}">See more</button>
      </li>`).join(`
`);o.insertAdjacentHTML("beforeend",n),o.addEventListener("click",z),o.addEventListener("click",P)}async function P(e){if(e.preventDefault(),e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let t=e.target.closest(".book-category-item").dataset.id;C(t)}}async function z(e){try{if(e.target.nodeName!=="BUTTON")return;let t=e.target.dataset.category;const o=document.querySelector(".sidebar-category-item"),n=document.querySelectorAll(".sidebar-category-item");window.scrollTo({top:0,behavior:"smooth"});const r=document.querySelector(".bestsellers-container");r.innerHTML="",u();const l=await d.getSelectedCategory(t);q(l,t),c(),n.forEach(a=>{a.dataset.source===t&&(o.classList.remove("category-active"),a.classList.add("category-active"),a.scrollIntoView({behavior:"instant",block:"center",inline:"nearest"}))}),window.scrollTo({top:0,behavior:"smooth"})}catch(t){console.log("Error fetching modal:",t)}}const L={categoryContainer:document.querySelector(".sidebar-category-container"),categoryList:document.querySelector(".sidebar-category-list"),allCategory:document.querySelector(".all-category")};function D(e){return e.sort((o,n)=>o.list_name.localeCompare(n.list_name)),e.map(o=>`<li class='sidebar-category-item' data-source="${o.list_name}">${o.list_name}</li>`).join("")}(async()=>{try{const e=document.querySelector(".bestsellers-container");e.innerHTML="",u();const t=await d.getCategoryList(),o=D(t);L.categoryList.insertAdjacentHTML("beforeend",o),c()}catch(e){console.log(e)}})();L.allCategory.addEventListener("click",async e=>{try{const t=document.querySelector(".bestsellers-container");t.innerHTML="",u();const o=await d.getBestSellers();E(o),c()}catch(t){console.log(t)}});L.categoryList.addEventListener("click",async e=>{if(e.target.classList.contains("sidebar-category-item")){const t=e.target.dataset.source;document.querySelectorAll(".sidebar-category-item").forEach(r=>{r.classList.remove("category-active")}),e.target.classList.add("category-active"),window.scrollTo({top:0,behavior:"smooth"});const n=document.querySelector(".bestsellers-container");n.innerHTML="",u();try{if(!e.target.classList.contains("all-category")){const r=await d.getSelectedCategory(t);q(r,t),c()}}catch(r){console.log(r)}}});N();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".scroll-up");e.classList.remove("show"),window.addEventListener("scroll",function(){window.scrollY>600?e.classList.add("show"):e.classList.remove("show")}),e.addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth"})})});function u(){document.querySelector(".loader-container").classList.remove("is-hidden-loader")}function c(){document.querySelector(".loader-container").classList.add("is-hidden-loader")}
//# sourceMappingURL=commonHelpers2.js.map
