import './js/CartPage/CardPagination/cardpagination';
import './js/CartPage/ShoppingList/shoppinglist';
import './js/MainPage/Header/header';
import './js/MainPage/MainMenu/MainPagination/mainpagination';
import './js/MainPage/MainMenu/MenuItem/menuitem';
import './js/MainPage/Sidebar/SidebarAllCategories/sidebarallcategories';
import './js/MainPage/Sidebar/SidebarSupport/sidebarsupport';
import './js/Servises/api';
import './js/Servises/helpers';
import './js/SignUp/signup';
import './js/SignUp/signupmarkup' 